#!/bin/bash

iterations=10

if [ $# -gt "0" ];
then
	CASE=$1
fi

if [ -z "${CASE}" ];
then
	echo "usage: $0 <case> [<iterations>]"
	exit 1
fi

if [ $# -gt "1" ];
then
	iterations=$2
fi

<< 'COMMENT'
echo "Total iterations: ${iterations}"
for t in 2 5 10 20 30 40 50;
do
	echo "Starting iterations for $t threads"
	echo "----------------------------------"
	export JMETER_THREADS=$t
	for i in `seq 1 $iterations`;
	do
		echo "---------------------"
		echo "Starting iteration $i"
		./run_wrapper.sh test_native_${t}threads.${i}
		sleep 5s
	done
done
COMMENT

for i in `seq 1 ${iterations}`;
do
	echo "---------------------"
	echo "Starting iteration $i"
	echo "---------------------"
	./run_wrapper.sh ${CASE}.${i}
	sleep 5s
done

